Import 3.0.20 source

diff --git a/contrib/bootstrap b/contrib/bootstrap
--- a/contrib/bootstrap
+++ b/contrib/bootstrap
@@ -36,7 +36,6 @@ usage()
 	echo "                   (USE AT YOUR OWN LEGAL RISKS)"
 	echo "  --disable-optim  disable optimization in libraries"
 	echo "  --enable-pdb     generate debug information in PDB format"
-	echo "  --enable-bitcode generate bitcode information"
 }
 
 BUILD=
@@ -52,7 +51,6 @@ GNUV3="1"
 AD_CLAUSES=
 WITH_OPTIMIZATION="1"
 ENABLE_PDB=
-ENABLE_BITCODE=
 
 while test -n "$1"
 do
@@ -84,9 +82,6 @@ do
 			;;
 		--enable-pdb)
 			ENABLE_PDB=1
-			;;
-		--enable-bitcode)
-			ENABLE_BITCODE=1
 			;;
 		--enable-small)
 			ENABLE_SMALL=1
@@ -124,7 +119,7 @@ fi
 if test -z "$BUILD"
 then
 	printf "Guessing build system... "
-	BUILD="`${CC:-cc} -dumpmachine`"
+	BUILD="`${CC:-cc} -dumpmachine | sed s/windows-gnu/mingw32/`"
 	if test -z "$BUILD"; then
 		echo "FAIL!"
 		exit 1
@@ -200,40 +195,40 @@ add_make_enabled()
 
 check_ios_sdk()
 {
-	if test "$VLCSDKROOT"
-	then
-		SDKROOT="$VLCSDKROOT"
-	else
+    if test "$VLCSDKROOT"
+    then
+	    SDKROOT="$VLCSDKROOT"
+    else
 		if test -z "$SDKROOT"
 		then
-			SDKROOT=`xcode-select -print-path`/Platforms/iPhone${PLATFORM}.platform/Developer/SDKs/iPhone${PLATFORM}${SDK_VERSION}.sdk
-			echo "SDKROOT not specified, assuming $SDKROOT"
+		   SDKROOT=`xcode-select -print-path`/Platforms/iPhone${PLATFORM}.platform/Developer/SDKs/iPhone${PLATFORM}${SDK_VERSION}.sdk
+		   echo "SDKROOT not specified, assuming $SDKROOT"
 		else
-			SDKROOT="$SDKROOT"
+		   SDKROOT="$SDKROOT"
 		fi
-	fi
+    fi
 
-	if [ ! -d "${SDKROOT}" ]
-	then
-		echo "*** ${SDKROOT} does not exist, please install required SDK, or set SDKROOT manually. ***"
-		exit 1
-	fi
-	add_make "IOS_SDK=${SDKROOT}"
+    if [ ! -d "${SDKROOT}" ]
+    then
+       echo "*** ${SDKROOT} does not exist, please install required SDK, or set SDKROOT manually. ***"
+       exit 1
+    fi
+    add_make "IOS_SDK=${SDKROOT}"
 }
 
 check_macosx_sdk()
 {
-	if [ -z "$SDKROOT" ]; then
-		SDKROOT=$(xcrun --sdk macosx --show-sdk-path)
-		echo "SDKROOT not specified, assuming $SDKROOT"
-	fi
+   if [ -z "$SDKROOT" ]; then
+      SDKROOT=$(xcrun --show-sdk-path)
+      echo "SDKROOT not specified, assuming $SDKROOT"
+   fi
 
-	if [ ! -d "$SDKROOT" ]; then
-		echo "*** $SDKROOT does not exist, please install required SDK, or set SDKROOT manually. ***"
-		exit 1
-	fi
+   if [ ! -d "$SDKROOT" ]; then
+      echo "*** $SDKROOT does not exist, please install required SDK, or set SDKROOT manually. ***"
+      exit 1
+   fi
 
-	add_make "MACOSX_SDK=${SDKROOT}"
+   add_make "MACOSX_SDK=${SDKROOT}"
 }
 
 check_android_sdk()
@@ -244,9 +239,21 @@ check_android_sdk()
 	add_make "ANDROID_ABI := ${ANDROID_ABI}"
 	[ -z "${ANDROID_API}" ] && echo "You should set ANDROID_API environment variable (using default android-9)" && ANDROID_API := android-9
 	add_make "ANDROID_API := ${ANDROID_API}"
+	[ ${ANDROID_ABI} = "armeabi-v7a" ] && add_make_enabled "HAVE_NEON"
 	[ ${ANDROID_ABI} = "armeabi-v7a" ] && add_make_enabled "HAVE_ARMV7A"
+	[ ${ANDROID_ABI} = "arm64-v8a" ] && add_make_enabled "HAVE_NEON"
 	[ ${ANDROID_ABI} = "arm64-v8a" ] && add_make_enabled "HAVE_ARMV8A"
 	[ ${ANDROID_ABI} = "armeabi" -a -z "${NO_ARMV6}" ] && add_make_enabled "HAVE_ARMV6"
+}
+
+check_tizen_sdk()
+{
+	[ -z "${TIZEN_SDK}" ] && echo "You must set TIZEN_SDK environment variable" && exit 1
+	add_make "TIZEN_SDK := ${TIZEN_SDK}"
+	[ -z "${TIZEN_ABI}" ] && echo "You must set TIZEN_ABI environment variable" && exit 1
+	add_make "TIZEN_ABI := ${TIZEN_ABI}"
+	[ ${TIZEN_ABI} = "armv7l" ] && add_make_enabled "HAVE_NEON"
+	[ ${TIZEN_ABI} = "armv7l" ] && add_make_enabled "HAVE_ARMV7A"
 }
 
 test -z "$PREFIX" || add_make "PREFIX := $PREFIX"
@@ -260,90 +267,121 @@ test -z "$AD_CLAUSES" || add_make_enabled "AD_CLAUSES"
 test -z "$WITH_OPTIMIZATION" || add_make_enabled "WITH_OPTIMIZATION"
 test -z "$ENABLE_PDB" || add_make_enabled "ENABLE_PDB"
 
+if [ "`uname -o 2>/dev/null`" = "Msys" ]; then
+    add_make "CMAKE_GENERATOR := MSYS Makefiles"
+    add_make "export CMAKE_GENERATOR"
+fi
+
 #
 # Checks
 #
 OS="${HOST#*-}" # strip architecture
-MAKE=make
 case "${OS}" in
 	*-darwin*)
 		if test -z "$BUILDFORIOS"
 		then
 			check_macosx_sdk
 			add_make_enabled "HAVE_MACOSX" "HAVE_DARWIN_OS" "HAVE_BSD"
+
+			case "${HOST}" in
+			    *arm64*|*aarch64*)
+			    add_make "PLATFORM_SHORT_ARCH := arm64"
+			    add_make_enabled "HAVE_NEON"
+			    ;;
+			    *x86_64*)
+			    add_make "PLATFORM_SHORT_ARCH := x86_64"
+			    ;;
+			esac;
 		else
 			check_ios_sdk
 			add_make_enabled "HAVE_IOS" "HAVE_DARWIN_OS" "HAVE_BSD" "HAVE_FPU"
 
 			case "${HOST}" in
-				*arm64*)
-					;;
-				*arm*)
-					add_make_enabled "HAVE_ARMV7A"
-					;;
+			    *armv7s*)
+			    add_make "PLATFORM_SHORT_ARCH := armv7s"
+			    add_make_enabled "HAVE_NEON" "HAVE_ARMV7A"
+			    ;;
+			    *arm*)
+			    add_make "PLATFORM_SHORT_ARCH := armv7"
+			    add_make_enabled "HAVE_NEON" "HAVE_ARMV7A"
+			    ;;
+			    *arm64*|*aarch64*)
+			    add_make "PLATFORM_SHORT_ARCH := arm64"
+			    ;;
+			    *x86_64*)
+			    add_make "PLATFORM_SHORT_ARCH := x86_64"
+			    ;;
+			    *86*)
+			    add_make "PLATFORM_SHORT_ARCH := i386"
+			    ;;
 			esac;
 		fi
 		if test "$BUILDFORTVOS"
 		then
 			add_make_enabled "HAVE_TVOS"
 		fi
-		if test "$ENABLE_BITCODE"
-		then
-			add_make_enabled "HAVE_BITCODE_ENABLED"
-		fi
 		;;
 	*bsd*)
-		MAKE=gmake
 		add_make_enabled "HAVE_BSD"
 		;;
 	*android*)
 		check_android_sdk
 		add_make_enabled "HAVE_LINUX" "HAVE_ANDROID"
 		case "${HOST}" in
-			*arm64*|*aarch64*)
-				add_make "PLATFORM_SHORT_ARCH := arm64"
-				;;
 			*arm*)
-				add_make "PLATFORM_SHORT_ARCH := arm"
-				;;
+			add_make "PLATFORM_SHORT_ARCH := arm"
+			;;
+			*arm64*|*aarch64*)
+			add_make "PLATFORM_SHORT_ARCH := arm64"
+			;;
 			*i686*)
-				add_make "PLATFORM_SHORT_ARCH := x86"
-				;;
+			add_make "PLATFORM_SHORT_ARCH := x86"
+			;;
 			*x86_64*)
-				add_make "PLATFORM_SHORT_ARCH := x86_64"
-				;;
+			add_make "PLATFORM_SHORT_ARCH := x86_64"
+			;;
 			*mipsel*)
-				add_make "PLATFORM_SHORT_ARCH := mips"
-				;;
+			add_make "PLATFORM_SHORT_ARCH := mips"
+			;;
 		esac
 		;;
 	*linux*)
+		if [ "`${CC} -v 2>&1 | grep tizen`" ]; then
+			check_tizen_sdk
+			add_make_enabled "HAVE_TIZEN"
+			case "${HOST}" in
+				*arm*)
+				add_make "PLATFORM_SHORT_ARCH := arm"
+				;;
+				*i386*)
+				add_make "PLATFORM_SHORT_ARCH := x86"
+				;;
+			esac
+		fi
+
 		add_make_enabled "HAVE_LINUX"
 		;;
 	*mingw*)
 		add_make_enabled "HAVE_WIN32"
 		case "${HOST}" in
 			*winphone*|*windowsphone*)
-				add_make_enabled "HAVE_WINDOWSPHONE"
-				;;
+			add_make_enabled "HAVE_WINDOWSPHONE"
+			;;
 		esac
 		case "${HOST}" in
 			*winphone*|*windowsphone*|*winrt*|*uwp*)
-				add_make_enabled "HAVE_WINSTORE"
-				;;
+			add_make_enabled "HAVE_WINSTORE"
+			;;
 		esac
 		case "${HOST}" in
-			armv7*)
-				add_make_enabled "HAVE_ARMV7A"
-				;;
-		esac
+            armv7*)
+                add_make_enabled "HAVE_ARMV7A"
+                ;;
+        esac
 		;;
 	*solaris*)
 		add_make_enabled "HAVE_SOLARIS"
 		;;
-	*emscripten*)
-	       add_make_enabled "HAVE_EMSCRIPTEN"
-	       ;;
 esac
 
 #
@@ -361,5 +399,5 @@ add_make "TOPDST = .."
 add_make "-include config.mak"
 add_make 'include $(TOPSRC)/src/main.mak'
 echo "Bootstrap completed."
-${MAKE} help
+make help
 mkdir -p $BOOTSTRAP_PATH/tarballs || exit $?
diff --git a/extras/tools/bootstrap b/extras/tools/bootstrap
--- a/extras/tools/bootstrap
+++ b/extras/tools/bootstrap
@@ -22,15 +22,15 @@ check_version() {
     gotver=$2
     gotmajor=`echo $gotver|cut -d. -f1`
     gotminor=`echo $gotver|cut -d. -f2`
-    gotmicro=`echo $gotver|cut -d. -f3|tr -c -d '[:digit:]'`
+    gotmicro=`echo $gotver|cut -d. -f3`
     [ -z "$gotmicro" ] && gotmicro=0
     needmajor=`echo $3|cut -d. -f1`
     needminor=`echo $3|cut -d. -f2`
     needmicro=`echo $3|cut -d. -f3`
     [ -z "$needmicro" ] && needmicro=0
-    if [ "$needmajor" -ne "$gotmajor" ] ||
-       [ "$needmajor" -eq "$gotmajor" -a "$needminor" -gt "$gotminor" ] ||
-       [ "$needmajor" -eq "$gotmajor" -a "$needminor" -eq "$gotminor" -a "$needmicro" -gt "$gotmicro" ];
+    if [ "$needmajor" -ne "$gotmajor" \
+         -o "$needmajor" -eq "$gotmajor" -a "$needminor" -gt "$gotminor" \
+         -o "$needmajor" -eq "$gotmajor" -a "$needminor" -eq "$gotminor" -a "$needmicro" -gt "$gotmicro" ]
     then
         echo "$1 too old"
         NEEDED="$NEEDED $1"
@@ -58,7 +58,7 @@ check_version_majmin() {
 }
 
 check_tar() {
-if ! tar PcJ /dev/null >/dev/null 2>&1 && ! tar PcJf /dev/null /dev/null 2>&1
+if ! tar PcJ /dev/null >/dev/null 2>&1
 then
     echo "tar doesn't support xz (J option)"
     NEEDED="$NEEDED tar xz"
@@ -96,28 +96,6 @@ else
 fi
 }
 
-check_ninja() {
-if ! ninja --version >/dev/null 2>&1
-then
-    echo "ninja not found"
-    NEEDED="$NEEDED ninja"
-else
-    jobserver=`ninja --version | head -1 | grep .jobserver`
-    if [ -z "$jobserver" ]; then
-        echo "ninja missing jobserver support"
-        NEEDED="$NEEDED ninja"
-    else
-        # found, need to check version ?
-        if [ -z "$1" ];then
-            FOUND="$FOUND ninja"
-        else
-            gotver=`ninja --version | head -1 | sed s/'.* '//`
-            check_version ninja $gotver $1
-        fi
-    fi
-fi
-}
-
 check() {
 if ! $1 --version >/dev/null 2>&1 && ! $1 -version >/dev/null 2>&1
 then
@@ -134,30 +112,47 @@ else
 fi
 }
 
+check_majmin() {
+if ! $1 --version >/dev/null 2>&1 && ! $1 -version >/dev/null 2>&1 && ! $1 --version 2>/dev/null
+then
+    echo "$1 not found"
+    NEEDED="$NEEDED $1"
+else
+    # found, need to check version ?
+    if [ -z "$2" ];then
+        FOUND="$FOUND $1"
+    else
+        gotver=`$1 --version | head -1 | sed s/'.* '//`
+        check_version_majmin $1 $gotver $2
+    fi
+fi
+}
+
 check autoconf 2.69
 check automake 1.15
 check m4 1.4.16
 check libtool 2.4
 check pkg-config
 check cmake 3.17.0
+check yasm
 check_tar
 check ragel
 check_sed
+check protoc 2.6.0
 check ant
 check xz
 check bison 3.0.0
 check flex
 check_nasm 2.14
-check gettext
 check help2man
-check meson 0.60.0
-check_ninja
+check meson 0.54.2
+check ninja
 
 DEPS_ONLY="help2man"
 
 CPUS=
 case `uname` in
-    Linux|MINGW32*|MINGW64*|*MSYS*)
+    Linux|MINGW32*|MINGW64*)
         CPUS=`getconf _NPROCESSORS_ONLN 2>&1`
      ;;
     Darwin|FreeBSD|NetBSD)
